// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIEVD3PQxJWwSz7YHDtaKWGar0jdgIHU',
    appId: '1:552639334958:web:da936292fa21a246d56dbf',
    messagingSenderId: '552639334958',
    projectId: 'todoapp-7d523',
    authDomain: 'todoapp-7d523.firebaseapp.com',
    storageBucket: 'todoapp-7d523.firebasestorage.app',
    measurementId: 'G-Z7HKY7WCS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzPn4MVlyAO8mXtMcCO-xlGGQ2bye7LJk',
    appId: '1:552639334958:android:87c43df1478ffd5dd56dbf',
    messagingSenderId: '552639334958',
    projectId: 'todoapp-7d523',
    storageBucket: 'todoapp-7d523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FhsMZO-iBkQrK_cuDlmQMXVNUsBkSkQ',
    appId: '1:552639334958:ios:6e3e668dc92784ebd56dbf',
    messagingSenderId: '552639334958',
    projectId: 'todoapp-7d523',
    storageBucket: 'todoapp-7d523.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6FhsMZO-iBkQrK_cuDlmQMXVNUsBkSkQ',
    appId: '1:552639334958:ios:6e3e668dc92784ebd56dbf',
    messagingSenderId: '552639334958',
    projectId: 'todoapp-7d523',
    storageBucket: 'todoapp-7d523.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuIEVD3PQxJWwSz7YHDtaKWGar0jdgIHU',
    appId: '1:552639334958:web:fcaed0a093b16147d56dbf',
    messagingSenderId: '552639334958',
    projectId: 'todoapp-7d523',
    authDomain: 'todoapp-7d523.firebaseapp.com',
    storageBucket: 'todoapp-7d523.firebasestorage.app',
    measurementId: 'G-XWKTBS2ST4',
  );
}
